routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->name('admin.')->group(function () {

    Route::get('/', 'RequisitionController@index');
    Route::get('/home', 'RequisitionController@index')->name('home');
    Route::post('/requests/{request}/approve', 'RequisitionController@approve')->name('requests.approve');
    Route::get('/requests/{request}/cancel', 'RequisitionController@cancellation')->name('requests.cancellation');
    Route::post('/requests/{request}/cancel', 'RequisitionController@cancel')->name('requests.cancel');
    Route::post('/requests/{request}/add-message', 'RequisitionController@addMessage')->name('requests.messages.add');
    Route::post('/requests/{request}/mark-message-read', 'RequisitionController@markMessageRead')->name('requests.messages.read');
    Route::resource('/requests', 'RequisitionController');
    /*Route::post('/pulls/{pull}/add-message', 'PullsController@addMessage')->name('pulls.messages.add');*/
    Route::put('/pulls/{pull}/pulled', 'PullsController@pulled')->name('pulls.pulled');
    Route::put('/pulls/{pull}/missing', 'PullsController@missing')->name('pulls.missing');
    Route::get('/pulls/{pull}/print', 'PullsController@print')->name('pulls.print');
    Route::resource('/pulls', 'PullsController');

});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {


    Route::get('/users/subjects/edit', 'SubjectUserController@edit')->name('users.subjects.edit');
    Route::put('/users/subjects/update', 'SubjectUserController@update')->name('users.subjects.update');

    Route::resource('/users', 'UserController');

    Route::get('/dashboard', 'DashboardController')->name('dashboard');

});

Auth::routes(['register' => false]);

app/Models/Patron.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Patron extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'inumber',
    ];

    public function getRolesAttribute($value) {
        return explode('|', $value);
    }

    public function setRolesAttribute($value) {
        if(is_array($value)){
            $this->attributes['roles'] = implode('|', $value);
        }else{
            $this->attributes['roles'] = '';
        }

    }

    /**
     * Get the patron's avatar link.
     *
     */
    public function getAvatarAttribute() {
        if(in_array('Employee', $this->roles)){
            return 'https://web.byui.edu/Directory/Employee/' . explode('@', $this->email)[0] . '.jpg';
        }
        return 'https://web.byui.edu/Directory/Student/' . explode('@', $this->email)[0] . '.jpg';
    }

    public function getFirstNameAttribute() {
        return explode(' ', $this->name)[0];
    }

    public function getLastFirstNameAttribute() {
        $name = explode(' ', $this->name);

        return end($name) . ', ' . $name[0];
    }

    public function getAffiliationAttribute() {
        return ((in_array('Employee', $this->roles))?'Employee':'Student');
    }

    static function findOrCreatePatronFromRequest($username){
        $patron = Patron::where('username', $username)->first();

        if(!is_null($patron)){
            return $patron;
        }

        $institution_username = "byui:$username";

        $provider = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId' => env('BYUI_OAUTH_CLIENTID'),    // The client ID assigned to you by the provider
            'clientSecret' => env('BYUI_OAUTH_CLIENTSECRET'),   // The client password assigned to you by the provider
            'redirectUri' => 'https://www.getpostman.com/oauth2/callback',
            'urlAuthorize' => env('BYUI_API_BASE_URL') . '/authorize',
            'urlAccessToken' => env('BYUI_API_BASE_URL') . '/token',
            'urlResourceOwnerDetails' => 'https://ids.byui.edu/oauth2/userinfo?schema=openid'
        ]);

        $accessToken = $provider->getAccessToken('client_credentials');
        $client = new \GuzzleHttp\Client();

        $response = $client->request('GET', env('BYUI_API_BASE_URL') . "/librarybridge/v1/cclaUser/".trim($institution_username),
            [
                'connect_timeout' => 20,
                'allow_redirects' => true,
                'timeout' => 2000,
                'headers' => [
                    'Authorization' => "Bearer $accessToken"
                ]
            ]);

        // Here the code for successful request

        $byuiUser = json_decode($response->getBody());

        $patron = new Patron();
        $patron->username = $username;
        $patron->name = $byuiUser->prefferedName . ' ' . $byuiUser->surname;
        if(strlen($byuiUser->personalContact->email) > 5){
            $patron->email = $byuiUser->personalContact->email;
        }else{
            $patron->email = $byuiUser->workContact->email;
        }
        $patron->inumber = $byuiUser->userId;
        $patron->roles = $byuiUser->roles;
        $patron->save();

        return $patron;

    }

    /**
     * Get all of the patron's requests.
     */
    public function requisitions()
    {
        return $this->hasMany(Requisition::class)->orderBy('created_at', 'DESC');
    }

    /**
     * Get all of the patron's messages.
     */
    public function messages()
    {
        return $this->morphMany(Message::class, 'messageable');
    }

}

app/Models/Requisition.php
<?php

namespace App;

use App\Enums\Status;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;

class Requisition extends Model
{
    use SoftDeletes, Userstamps;

    protected $fillable = [
        'channel',
    ];

    protected $dates = [
        'approved_at',
        'purchase_request_sent_at',
        'received_at',
    ];

    public function patron()
    {
        return $this->belongsTo(Patron::class);
    }

    public function librarian()
    {
        return $this->belongsTo(User::class);
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class);
    }

    public function formats()
    {
        return $this->hasMany(Format::class);
    }

    /**
     * The messages for the job
     */
    public function messages()
    {
        return $this->hasMany(Message::class)
                    ->orderBy('created_at', 'DESC');
    }

    public function getDisplayTnNumberAttribute() {
        if(is_null($this->tn_number)){
            return 'Purchase Request';
        }
        return $this->tn_number;
    }

    /**
     * Scope a query to requests needing attention.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNewPurchase($query)
    {
        return $query->where('status', Status::NEW_PURCHASE_REQUEST);
    }

    /**
     * Scope a query to requests needing attention.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNewPull($query)
    {
        return $query->where('pulled', 0);
    }

    /**
     * Scope a query to requests needing attention.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeAttention($query)
    {
        return $query->where('ill_needs_updated', 1);
    }

    /**
     * Scope a query to overdue requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOverdue($query)
    {
        return $query->where('created_at', '<', now()->subHours(24))
                        ->where('status', Status::PENDING_APPROVAL);
    }

    /**
     * Scope a query to ill requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeIll($query)
    {
        return $query->where('status', Status::APPROVED_FOR_ILL);
    }

    /**
     * Scope a query to ordered requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOrdered($query)
    {
        return $query->where('status', Status::ORDERED);
    }

    /**
     * Scope a query to cancelled requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCancelled($query)
    {
        return $query->where('status', Status::CANCELLED);
    }

    /**
     * Scope a query to limit requests to user.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLimitToUser($query)
    {
        return $query->where('librarian_id', user()->id);
    }

    /**
     * Scope a query to limit requests to search terms.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSearch($query, $term)
    {
        return $query->where(function(Builder $query) use ($term){
            $query->whereHas('patron', function(Builder $q) use ($term){
                $q->where('name', 'LIKE', '%'.$term.'%');
            })
                ->orWhere('tn_number', 'LIKE', '%'.$term.'%')
                ->orWhere('title', 'LIKE', '%'.$term.'%');
        });
    }

    /**
     * Scope a query to limit requests to status.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeStatus($query, $status)
    {
        return $query->where('status', $status);
    }

    /**
     * Scope a query to limit requests to status.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeHasMessage($query)
    {
        return $query->where('librarian_added_note', 1);
    }

}

resources/views/admin/ill/requisitions/cancellation.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Cancel Purchase Request</h1>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open()->fill($requisition)->id('requisition-cancellation')->post()->route('admin.requests.cancel', ['request' => $requisition]) !!}

                            <div class="row">
                                <div class="col col-md col-lg">
                                    {!! Form::select('cancellation', 'Reason', ([null => '-- Select one --'] + $reasons), request('reason'))->required(true) !!}
                                </div>
                            </div>

                            @if($reason)
                                <div class="row">
                                    <div class="col col-md col-lg">
                                        {!! Form::textarea('body', 'Email Message', $reason->description)->required(false)->attrs(['class' => 'summernote']) !!}
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="row">
                                        <button class="btn btn-primary btn-block" type="submit">SEND</button>
                                    </div>
                                </div>
                            @endif

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>

        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script>
        $(function(){
            $(document).on('change', '#cancellation', function(e){
                e.preventDefault();
                window.location = '{{ route('admin.requests.cancellation', ['request' => $requisition]) }}?reason=' + $(this).val();
            });
        })
    </script>
@endpush

resources/views/admin/ill/requisitions/create.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Create New Request</h1>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open()->fill($requisition)->id('requisition-approval')->post()->route('admin.requests.store') !!}
                            @include('admin.ill.requisitions.form')
                            <div class="card-footer">
                                <div class="row">
                                    <button class="btn btn-primary btn-block" type="submit">SAVE</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            {{--<div class="col-lg-4 col-md-12 col-12 col-sm-12">
                @if($pendingRequests->count() > 0)
                    <div class="card">
                        <div class="card-header">
                            Pending Requests
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled list-unstyled-border">
                                @foreach($pendingRequests as $key => $pendingRequest)
                                <li class="media pending-request" data-id="{{ $key }}">
                                    <div class="media-body">
                                        <div class="media-right">{{ $pendingRequest->TransactionNumber }}</div>
                                        <div class="media-title">{{ $pendingRequest->LoanTitle }}</div>
                                        <div class="text-muted text-small">by {{ $pendingRequest->LoanAuthor }}</div>
                                    </div>
                                </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
            </div>--}}
        </div>
        {!! Form::open()->id('search-patrons-form')->get()->route('admin.requests.create') !!}
            {!! Form::hidden('tn_number', '') !!}
        {!! Form::close() !!}
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script>
        $(function(){
            $(document).on('click', '#search-patrons', function(e){
                e.preventDefault();
                var $button = $(this);
                var $form = $('#search-patrons-form');
                var $tn = $form.find('#tn_number');
                $tn.val($('#requisition-approval').find('#tn_number').val());
                $form.submit();
            });
        })
    </script>
@endpush

resources/views/admin/ill/requisitions/edit.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Edit Request</h1>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open()->fill($requisition)->id('requisition-approval')->put()->route('admin.requests.update', ['request' => $requisition]) !!}
                            @include('admin.ill.requisitions.form')
                            <div class="card-footer">
                                <div class="row">
                                    <button class="btn btn-primary btn-block" type="submit">SAVE</button>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script>
        $(function(){

        })
    </script>
@endpush

resources/views/admin/ill/requisitions/index.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Requests</h1>
        </div>

        <div class="row">
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.home', ['status' => \App\Enums\Status::NEW_PURCHASE_REQUEST]) }}" class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-success">
                        <i class="fas fa-concierge-bell"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>New Purchase Request</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['new_purchase_request'] }}
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.pulls.index') }}" class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-warning">
                        <i class="fas fa-truck"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Pull Requests</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['new_pull_request'] }}
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.home', ['status' => \App\Enums\Status::PENDING_APPROVAL, 'state' => 'overdue']) }}"  class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-danger">
                        <i class="far fa-clock"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Expired Approval</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['overdue'] }}
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.home', ['status' => \App\Enums\Status::APPROVED_FOR_ILL]) }}"  class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-info">
                        <i class="far fa-share-square"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Ill Approved</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['ill_approved'] }}
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.home', ['status' => \App\Enums\Status::ORDERED]) }}"  class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-primary">
                        <i class="fas fa-shopping-cart"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Ordered</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['ordered'] }}
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6 col-12">
                <a href="{{ route('admin.home', ['status' => \App\Enums\Status::CANCELLED]) }}"  class="card card-statistic-1 mb-2">
                    <div class="card-icon bg-secondary">
                        <i class="fas fa-ban"></i>
                    </div>
                    <div class="card-wrap">
                        <div class="card-header">
                            <h4>Cancelled</h4>
                        </div>
                        <div class="card-body">
                            {{ $stats['cancelled'] }}
                        </div>
                    </div>
                </a>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card mb-2">
                    <div class="card-body px-4 pt-1 pb-0">
                        <form action="{{ route('admin.requests.index') }}" class="form" method="get">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="q">Search by Name, TN Number, or Title</label>
                                        <input type="search" class="form-control" id="q" name="q" value="{{ request()->get('q', '') }}">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    {!! Form::select('status', 'Status', $statuses, request()->get('status', null))->required(false) !!}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-striped table-md table-hover">
                                <tbody>
                                    <tr>
                                        <th>TN Number</th>
                                        <th>Status</th>
                                        <th>Date Requested</th>
                                        <th>Title</th>
                                        <th>Librarian</th>
                                        <th>Patron</th>
                                        <th>Type</th>
                                    </tr>
                                    @foreach ($requisitions as $requisition)
                                        <tr @if($requisition->ill_needs_updated == 1) class="table-warning" @elseif($requisition->status == \App\Enums\Status::NEW_PURCHASE_REQUEST) class="table-danger" @endif style="cursor: pointer;" onclick="javascript: window.location.href = '{{ route('admin.requests.show', ['request' => $requisition]) }}'">
                                            <td>
                                                {{--<a href="{{ route('admin.requests.show', ['request' => $requisition]) }}" style="padding: 6px 8px">--}}
                                                    {{ $requisition->display_tn_number }}
                                                {{--</a>--}}
                                            </td>
                                            <td>
                                                @if($requisition->librarian_added_note)
                                                    <i class="far fa-sticky-note text-info"></i>
                                                @endif
                                                {{ \App\Enums\Status::valueForKey($requisition->status) }}
                                            </td>
                                            <td>
                                                {{ $requisition->created_at->format('m-d-Y') }}
                                            </td>
                                            <td>
                                                {{--<a href="{{route('admin.requests.show', ['request' => $requisition]) }}" style="padding: 6px 8px">--}}
                                                    {{ $requisition->title }}
                                                {{--</a>--}}
                                            </td>
                                            <td>
                                                @if($requisition->librarian)
                                                    {{ $requisition->librarian->name }}
                                                @endif
                                            </td>
                                            <td>
                                                {{ $requisition->patron->name }}
                                            </td>
                                            <td>
                                                {{ $requisition->patron->affiliation }}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>

                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-left">
                        <nav class="d-inline-block">
                            {!! $requisitions->appends(request()->all())->links() !!}
                        </nav>
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script src="{{ asset('assets/js/page/components-table.js') }}"></script>
    <script>
        $(function(){
            $(document).on('change', '#status', function(){
                $(this).closest('form').submit();
            });
        });
    </script>
@endpush