routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->name('admin.')->group(function () {

    Route::get('/', 'RequisitionController@index');
    Route::get('/home', 'RequisitionController@index')->name('home');
    Route::post('/requests/{request}/approve', 'RequisitionController@approve')->name('requests.approve');
    Route::get('/requests/{request}/cancel', 'RequisitionController@cancellation')->name('requests.cancellation');
    Route::post('/requests/{request}/cancel', 'RequisitionController@cancel')->name('requests.cancel');
    Route::post('/requests/{request}/add-message', 'RequisitionController@addMessage')->name('requests.messages.add');
    Route::post('/requests/{request}/mark-message-read', 'RequisitionController@markMessageRead')->name('requests.messages.read');
    Route::resource('/requests', 'RequisitionController');
    /*Route::post('/pulls/{pull}/add-message', 'PullsController@addMessage')->name('pulls.messages.add');*/
    Route::put('/pulls/{pull}/pulled', 'PullsController@pulled')->name('pulls.pulled');
    Route::put('/pulls/{pull}/missing', 'PullsController@missing')->name('pulls.missing');
    Route::get('/pulls/{pull}/print', 'PullsController@print')->name('pulls.print');
    Route::resource('/pulls', 'PullsController');

});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {


    Route::get('/users/subjects/edit', 'SubjectUserController@edit')->name('users.subjects.edit');
    Route::put('/users/subjects/update', 'SubjectUserController@update')->name('users.subjects.update');

    Route::resource('/users', 'UserController');

    Route::get('/dashboard', 'DashboardController')->name('dashboard');

});

Auth::routes(['register' => false]);

app/Models/Patron.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Patron extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'inumber',
    ];

    public function getRolesAttribute($value) {
        return explode('|', $value);
    }

    public function setRolesAttribute($value) {
        if(is_array($value)){
            $this->attributes['roles'] = implode('|', $value);
        }else{
            $this->attributes['roles'] = '';
        }

    }

    /**
     * Get the patron's avatar link.
     *
     */
    public function getAvatarAttribute() {
        if(in_array('Employee', $this->roles)){
            return 'https://web.byui.edu/Directory/Employee/' . explode('@', $this->email)[0] . '.jpg';
        }
        return 'https://web.byui.edu/Directory/Student/' . explode('@', $this->email)[0] . '.jpg';
    }

    public function getFirstNameAttribute() {
        return explode(' ', $this->name)[0];
    }

    public function getLastFirstNameAttribute() {
        $name = explode(' ', $this->name);

        return end($name) . ', ' . $name[0];
    }

    public function getAffiliationAttribute() {
        return ((in_array('Employee', $this->roles))?'Employee':'Student');
    }

    static function findOrCreatePatronFromRequest($username){
        $patron = Patron::where('username', $username)->first();

        if(!is_null($patron)){
            return $patron;
        }

        $institution_username = "byui:$username";

        $provider = new \League\OAuth2\Client\Provider\GenericProvider([
            'clientId' => env('BYUI_OAUTH_CLIENTID'),    // The client ID assigned to you by the provider
            'clientSecret' => env('BYUI_OAUTH_CLIENTSECRET'),   // The client password assigned to you by the provider
            'redirectUri' => 'https://www.getpostman.com/oauth2/callback',
            'urlAuthorize' => env('BYUI_API_BASE_URL') . '/authorize',
            'urlAccessToken' => env('BYUI_API_BASE_URL') . '/token',
            'urlResourceOwnerDetails' => 'https://ids.byui.edu/oauth2/userinfo?schema=openid'
        ]);

        $accessToken = $provider->getAccessToken('client_credentials');
        $client = new \GuzzleHttp\Client();

        $response = $client->request('GET', env('BYUI_API_BASE_URL') . "/librarybridge/v1/cclaUser/".trim($institution_username),
            [
                'connect_timeout' => 20,
                'allow_redirects' => true,
                'timeout' => 2000,
                'headers' => [
                    'Authorization' => "Bearer $accessToken"
                ]
            ]);

        // Here the code for successful request

        $byuiUser = json_decode($response->getBody());

        $patron = new Patron();
        $patron->username = $username;
        $patron->name = $byuiUser->prefferedName . ' ' . $byuiUser->surname;
        if(strlen($byuiUser->personalContact->email) > 5){
            $patron->email = $byuiUser->personalContact->email;
        }else{
            $patron->email = $byuiUser->workContact->email;
        }
        $patron->inumber = $byuiUser->userId;
        $patron->roles = $byuiUser->roles;
        $patron->save();

        return $patron;

    }

    /**
     * Get all of the patron's requests.
     */
    public function requisitions()
    {
        return $this->hasMany(Requisition::class)->orderBy('created_at', 'DESC');
    }

    /**
     * Get all of the patron's messages.
     */
    public function messages()
    {
        return $this->morphMany(Message::class, 'messageable');
    }

}

app/Models/Pull.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Wildside\Userstamps\Userstamps;

class Pull extends Model
{

    use SoftDeletes, Userstamps;

    public function patron()
    {
        return $this->belongsTo(Patron::class);
    }

    /**
     * The messages for the job
     */
    /*public function messages()
    {
        return $this->hasMany(Message::class)->orderBy('created_at', 'DESC');
    }*/

    /**
     * Scope a query to new pull requests.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeNewpull($query)
    {
        return $query->where('pulled', 0);
    }

}

app/Http/Controllers/PullsController.php
<?php

namespace App\Http\Controllers;

use App\Message;
use App\Notifications\PullRequestReady;
use App\Pull;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class PullsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pulls = Pull::where('pulled', 0);

        if($request->has('status')){
            $pulls = new Pull();
            if($request->get('status') == 'pending'){
                $pulls = $pulls->where('pulled', 0);
            }

            if($request->get('status') == 'pulled'){
                $pulls = $pulls->where('pulled', 1);
            }

            if($request->get('status') == 'cancelled'){
                $pulls = $pulls->onlyTrashed();
            }

            if($request->get('status') == 'all'){
                $pulls = $pulls->withTrashed();
            }
        }

        if($request->has('q')){
            $pulls = $pulls->where(function(Builder $query) use ($request){
                $query->whereHas('patron', function(Builder $q) use ($request){
                    $q->where('name', 'LIKE', '%'.$request->get('q').'%');
                })
                    ->orWhere('title', 'LIKE', '%'.$request->get('q').'%');
            });
        }

        $pulls = $pulls->paginate(25);

        return view('admin.ill.pulls.index', [
            'pulls' => $pulls,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  Pull $pull
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pull = Pull::where('id', $id)->withTrashed()->first();

        return view('admin.ill.pulls.show' , [
            'pull' => $pull
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Pull $pull
     * @return \Illuminate\Http\Response
     */
    public function edit(Pull $pull)
    {
        $patron = $pull->patron;

        return view('admin.ill.pulls.edit', [
            'pull' => $pull,
            'patron' => $patron,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pull $pull)
    {
        $pull->title = $request->get('title');
        $pull->author = $request->get('author');
        $pull->call_number = $request->get('call_number');
        $pull->location = $request->get('location');
        $pull->barcode = $request->get('barcode');
        $pull->save();

        return redirect()->route('admin.pulls.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Pull $pull
     * @return \Illuminate\Http\Response
     */
    public function pulled(Request $request, $id)
    {
        $pull = Pull::withTrashed()->where('id', $id)->first();

        if($pull->patron->affiliation == 'Student') {
            $client = new \GuzzleHttp\Client();

            $response = $client->request('GET', 'http://abish.byui.edu/horizon/api/index.cfm/pulled/' . $request->get('barcode'),
                [
                    'connect_timeout' => 20,
                    'allow_redirects' => true,
                    'timeout' => 2000,
                    'headers' => [
                        'Authorization' => "Bearer " . env('HORIZON_API_KEY')
                    ]
                ]);
            $pull->barcode = $request->get('barcode');
        }

        $pull->pulled = 1;
        $pull->save();

        if($pull->patron->affiliation == 'Student'){
            $pull->patron->notify(new PullRequestReady($pull));
        }

        return redirect()->route('admin.pulls.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Pull $pull
     * @return \Illuminate\Http\Response
     */
    public function missing(Request $request, Pull $pull)
    {

        switch($request->get('action')){


            case 'not-found':
                $pull->patron->notify(new \App\Notifications\PullNotFound($pull));
                /*$pull->messages()->save(new Message([
                    'body' => user()->name . ' could not find this item.',
                ]));*/
                break;

            case 'lost':
                $pull->patron->notify(new \App\Notifications\PullCancelled($pull));
                /*$pull->messages()->save(new Message([
                    'body' => user()->name . ' cancelled this pull request.',
                ]));*/
                $pull->delete();
                break;
        }

        return redirect()->route('admin.pulls.index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Pull $pull
     * @return \Illuminate\Http\Response
     */
    public function print(Request $request, Pull $pull)
    {

        return view('admin.ill.pulls.print' , [
            'pull' => $pull
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pull $pull)
    {
        $pull->delete();

        return redirect()->route('admin.pulls.index');
    }
}

resources/views/admin/ill/pulls/edit.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Edit Pull Request</h1>
            <div class="section-header-breadcrumb">
                {!!Form::open()->attrs(['class' => 'delete-form'])->delete()->route('admin.pulls.destroy', ['pull' => $pull])!!}
                {!! Form::submit("Delete")->danger() !!}
                {!!Form::close()!!}
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open()->fill($pull)->put()->route('admin.pulls.update', ['pull' => $pull]) !!}
                            @include('admin.ill.pulls.form')
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-12 col-md-12 col-lg-12">
                                        <button class="btn btn-primary btn-block" type="submit">SAVE</button>
                                    </div>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script>
        $(function(){

        })
    </script>
@endpush

resources/views/admin/ill/pulls/form.blade.php
{!! Form::fieldsetOpen('Patron Information') !!}
    {!! Form::hidden('id', $patron->id) !!}
    <div class="row">
        <div class="col col-md col-lg">
            {!! Form::text('name', 'Name', $patron->name)->attrs(['readonly' => true])->required() !!}
        </div>
        <div class="col col-md col-lg">
            {!! Form::text('email', 'Email', $patron->email)->attrs(['readonly' => true])->required() !!}
        </div>
        <div class="col col-md col-lg">
            {!! Form::text('inumber', 'I#', $patron->inumber)->attrs(['readonly' => true])->required() !!}
        </div>
    </div>

{!! Form::fieldsetClose() !!}

{!! Form::fieldsetOpen('Request Information') !!}

    <div class="row">
        <div class="col-5 col-md-5 col-lg-5">
            {!! Form::text('title', 'Title')->required(false) !!}
        </div>
        <div class="col-2 col-md-5 col-lg-5">
            {!! Form::text('author', 'Author')->required(false) !!}
        </div>
    </div>

    <div class="row">
        <div class="col-5 col-md-5 col-lg-5">
            {!! Form::text('location', 'Location')->required(false) !!}
        </div>
        <div class="col-2 col-md-5 col-lg-5">
            {!! Form::text('call_number', 'Call #')->required() !!}
        </div>
    </div>


{!! Form::fieldsetClose() !!}


@push('scripts')

@endpush

resources/views/admin/ill/pulls/index.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Pull Requests</h1>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card mb-2">
                    <div class="card-body px-4 pt-1 pb-0">
                        <form action="{{ route('admin.pulls.index') }}" class="form" method="get">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="q">Search by Name or Title</label>
                                        <input type="search" class="form-control" id="q" name="q" value="{{ request()->get('q', '') }}">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    {!! Form::select('status', 'Status', [
                                            'pending' => 'Pending',
                                            'pulled' => 'Pulled',
                                            'cancelled' => 'Cancelled',
                                            'all' => 'All',
                                        ],
                                        request()->get('status', 'pending'))->required(false) !!}
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-striped table-md table-hover">
                                <tbody>
                                    <tr>
                                        <th>Patron Type</th>
                                        <th>Patron Name</th>
                                        <th>Request Date</th>
                                        <th>Title</th>
                                        <th>Author</th>
                                        <th>Location</th>
                                        <th>Call #</th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                    </tr>
                                    @foreach ($pulls as $pull)
                                        <tr style="cursor: pointer;" class="@if($pull->deleted_at) table-danger @elseif($pull->pulled) table-success @else @endif">
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{--<a href="{{ route('admin.requests.show', ['request' => $requisition]) }}" style="padding: 6px 8px">--}}
                                                    {{ $pull->patron->affiliation }}
                                                {{--</a>--}}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->patron->last_first_name }}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->created_at->format('m-d-Y') }}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->title }}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->author }}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->location }}
                                            </td>
                                            <td onclick="javascript: window.location.href = '{{ route('admin.pulls.show', ['pull' => $pull]) }}'">
                                                {{ $pull->call_number }}
                                            </td>
                                            <td>
                                                {{--@if($pull->patron->affiliation == 'Employee'  && $pull->pulled != 1)@if($pull->patron->affiliation == 'Employee'  && $pull->pulled != 1)
                                                    {!! Form::open()->put()->route('admin.pulls.pulled', ['pull' => $pull]) !!}
                                                        {!! Form::submit("Pulled")->success()->attrs(['name' => "action", 'value' => "pulled"]) !!}
                                                    {!! Form::close()!!}
                                                @endif--}}
                                            </td>
                                            <td>
                                                <a href="{{ route('admin.pulls.print', ['pull' => $pull]) }}" class="btn btn-dark" target="_blank" rel="noreferrer noopener">
                                                    Print
                                                </a>
                                            </td>
                                            <td>
                                                {!! Form::open()->get()->route('admin.pulls.edit', ['pull' => $pull]) !!}
                                                    {!! Form::submit("Edit")->info() !!}
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                                <tfoot>

                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="card-footer text-left">
                        <nav class="d-inline-block">
                            {!! $pulls->appends(request()->all())->links() !!}
                        </nav>
                    </div>
                </div>

            </div>
        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script src="{{ asset('assets/js/page/components-table.js') }}"></script>
    <script>
        $(function(){
            $(document).on('change', '#status', function(){
                $(this).closest('form').submit();
            });
        });
    </script>
    {{--<script>
        $(function(){
            $(document).on('click', 'a.btn-dark', function(e){
                e.stopPropagation();
            });
        });
    </script>--}}
@endpush

resources/views/admin/ill/pulls/print.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
{{--<script src="{{ asset('js/app.js') }}" defer></script>--}}

<!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- General CSS Files -->
    <link rel="stylesheet" href="{{ asset('assets/modules/bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/ionicons/css/ionicons.min.css') }}">

    <!-- Template CSS -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/components.css') }}">


    @stack('css')
    <style>
        table {
            font-size: 24px;
        }
    </style>
</head>
<body class="sidebar-mini" style="margin-top: 300px;">

        <table class="table table-striped">
            <tbody>
                <tr>
                    <th style="width: 20%;">Patron Name</th>
                    <td  style="width: 80%;">
                        {{ $pull->patron->last_first_name }}
                    </td>
                </tr>
                @if($pull->patron->affiliation == 'Employee')
                    <tr>
                        <th>Office</th>
                        <td>
                            {{ $pull->patron->office }}
                        </td>
                    </tr>
                @endif
                <tr>
                    <th>Patron Type</th>
                    <td>
                        {{ $pull->patron->affiliation }}
                    </td>
                </tr>
                <tr>
                    <th>Request Date</th>
                    <td>
                        {{ $pull->created_at->format('m-d-Y') }}
                    </td>
                </tr>
                <tr>
                    <th>Title</th>
                    <td>
                        {{ $pull->title }}
                    </td>
                </tr>
                <tr>
                    <th>Author</th>
                    <td>
                        {{ $pull->author }}
                    </td>
                </tr>
                <tr>
                    <th>Location</th>
                    <td>
                        {{ $pull->location }}
                    </td>
                </tr>
                <tr>
                    <th>Call #</th>
                    <td>
                        {{ $pull->call_number }}
                    </td>
                </tr>
            </tbody>
            <tfoot>

            </tfoot>
        </table>

    <!-- General JS Scripts -->
    <script src="{{ asset('assets/modules/jquery.min.js') }}"></script>
    <script>
        $(function(){
            window.print();
        });
    </script>
</body>
</html>

resources/views/admin/ill/pulls/show.blade.php
@extends('layouts.admin')

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Edit Pull Request</h1>
            <div class="section-header-breadcrumb">
                {!!Form::open()->attrs(['class' => 'missing-form'])->put()->route('admin.pulls.missing', ['pull' => $pull])!!}
                    <button class="btn btn-info" type="submit" name="action" value="not-found">
                        <i class="fas fa-envelope"></i>
                        ITEM MISSING
                    </button>
                {!!Form::close()!!}
                {!!Form::open()->attrs(['class' => 'missing-form'])->put()->route('admin.pulls.missing', ['pull' => $pull])!!}
                    <button class="btn btn-outline-danger" type="submit" name="action" value="lost">
                        <i class="fas fa-envelope"></i>
                        CANCEL REQUEST
                    </button>
                {!!Form::close()!!}
                {!!Form::open()->attrs(['class' => 'delete-form'])->delete()->route('admin.pulls.destroy', ['pull' => $pull])!!}
                    {!! Form::submit("Delete")->danger() !!}
                {!!Form::close()!!}
            </div>
        </div>

        <div class="row">
            <div class="col-lg-8 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        {!! Form::open()->fill($pull)->put()->route('admin.pulls.pulled', ['pull' => $pull]) !!}
                            @include('admin.ill.pulls.form', ['patron' => $pull->patron])
                            @if($pull->patron->affiliation != 'Employee')
                                <div class="row">
                                    <div class="col-12 col-md-12 col-lg-12">
                                        {!! Form::text('barcode', 'Barcode')->attrs(['autofocus' => true])->required(false) !!}
                                    </div>
                                </div>
                            @endif
                            <div class="card-footer">
                                <div class="row">
                                    <div class="col-12 col-md-12 col-lg-12">
                                        <button class="btn btn-primary btn-block" type="submit" name="action" value="pulled">MARK PULLED</button>
                                    </div>
                                </div>
                            </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            {{--<div class="col-lg-4 col-md-12 col-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Recent Activities</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled list-unstyled-border">
                            @foreach($pull->messages as $message)
                                <li class="media">
                                    @if($message->messageable_id)
                                        <i class="far fa-sticky-note mr-3 rounded-circle" style="width: 50px; height: 50px;"></i>
                                    @else
                                        <i class="fas fa-cogs mr-3 rounded-circle" style="width: 50px; height: 50px;"></i>
                                    @endif
                                    <div class="media-body">
                                        <div class="float-right text-primary">{{ $message->created_at->toDayDateTimeString() }}</div>
                                        @if($message->messageable_id)
                                            <div class="media-title">{{ $message->messageable->name }}</div>
                                        @else
                                            <div class="media-title">System</div>
                                        @endif
                                        <span class="text-small text-muted">
                                            {!! $message->body !!}
                                        </span>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                        {!! Form::open()->post()->route('admin.pulls.messages.add', ['pull' => $pull]) !!}
                            <textarea name="body" class="summernote-simple"></textarea>
                            <button class="btn btn-block btn-primary" type="submit">ADD NOTE</button>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>--}}
        </div>
    </section>

@endsection


@push('css')
    <style>
        .missing-form{
            margin-right: 12px;
        }
    </style>
@endpush

@push('scripts')
    <script>
        $(function(){

        })
    </script>
@endpush