routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->name('admin.')->group(function () {

    Route::get('/', 'RequisitionController@index');
    Route::get('/home', 'RequisitionController@index')->name('home');
    Route::post('/requests/{request}/approve', 'RequisitionController@approve')->name('requests.approve');
    Route::get('/requests/{request}/cancel', 'RequisitionController@cancellation')->name('requests.cancellation');
    Route::post('/requests/{request}/cancel', 'RequisitionController@cancel')->name('requests.cancel');
    Route::post('/requests/{request}/add-message', 'RequisitionController@addMessage')->name('requests.messages.add');
    Route::post('/requests/{request}/mark-message-read', 'RequisitionController@markMessageRead')->name('requests.messages.read');
    Route::resource('/requests', 'RequisitionController');
    /*Route::post('/pulls/{pull}/add-message', 'PullsController@addMessage')->name('pulls.messages.add');*/
    Route::put('/pulls/{pull}/pulled', 'PullsController@pulled')->name('pulls.pulled');
    Route::put('/pulls/{pull}/missing', 'PullsController@missing')->name('pulls.missing');
    Route::get('/pulls/{pull}/print', 'PullsController@print')->name('pulls.print');
    Route::resource('/pulls', 'PullsController');

});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {


    Route::get('/users/subjects/edit', 'SubjectUserController@edit')->name('users.subjects.edit');
    Route::put('/users/subjects/update', 'SubjectUserController@update')->name('users.subjects.update');

    Route::resource('/users', 'UserController');

    Route::get('/dashboard', 'DashboardController')->name('dashboard');

});

Auth::routes(['register' => false]);

app/Models/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    protected $connection = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'receive_purchase_notifications'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get all of the user's messages.
     */
    public function messages()
    {
        return $this->morphMany(Message::class, 'messageable');
    }

    public function getFirstNameAttribute() {
        return explode(' ', $this->name)[0];
    }
}

resources/views/layouts/sections/alerts.blade.php
@if(auth()->check())

@if(!empty($stats['messages']))
    <li class="item">
        <a href="{{ route('admin.home', ['messages' => 1]) }}" class="nav-link nav-link-lg @if($stats['messages'] > 0) beep @endif">
            <i class="far fa-sticky-note"></i>
        </a>
    </li>
@endif

<li class="dropdown dropdown-list-toggle">
    <a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg @if(auth()->user()->notifications->count() > 0) beep @endif ">
        <i class="far fa-bell"></i>
    </a>
    <div class="dropdown-menu dropdown-list dropdown-menu-right">
        <div class="dropdown-header">Notifications
            <div class="float-right">
                <a href="#">Mark All As Read</a>
            </div>
        </div>
        <div class="dropdown-list-content dropdown-list-icons">
            {{--@foreach(auth()->user()->notifications as $notification)
                <a href="#" class="dropdown-item dropdown-item-unread">
                    <div class="dropdown-item-icon bg-primary text-white">
                        <i class="fas fa-bell"></i>
                    </div>
                    <div class="dropdown-item-desc">
                        {{ $notification->data['message'] }}
                        <div class="time text-primary">{{ $notification->created_at->diffForHumans() }}</div>
                    </div>
                </a>
            @endforeach--}}
        </div>
        {{--<div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
        </div>--}}
    </div>
</li>
@endif

resources/views/layouts/sections/messages.blade.php
<li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
    <div class="dropdown-menu dropdown-list dropdown-menu-right">
        <div class="dropdown-header">Messages
            <div class="float-right">
                <a href="#">Mark All As Read</a>
            </div>
        </div>
        <div class="dropdown-list-content dropdown-list-message">
            <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="assets/img/avatar/avatar-1.png" class="rounded-circle">
                    <div class="is-online"></div>
                </div>
                <div class="dropdown-item-desc">
                    <b>Kusnaedi</b>
                    <p>Hello, Bro!</p>
                    <div class="time">10 Hours Ago</div>
                </div>
            </a>
            <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="assets/img/avatar/avatar-2.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Dedik Sugiharto</b>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    <div class="time">12 Hours Ago</div>
                </div>
            </a>
            <a href="#" class="dropdown-item dropdown-item-unread">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="assets/img/avatar/avatar-3.png" class="rounded-circle">
                    <div class="is-online"></div>
                </div>
                <div class="dropdown-item-desc">
                    <b>Agung Ardiansyah</b>
                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <div class="time">12 Hours Ago</div>
                </div>
            </a>
            <a href="#" class="dropdown-item">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="assets/img/avatar/avatar-4.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Ardian Rahardiansyah</b>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                    <div class="time">16 Hours Ago</div>
                </div>
            </a>
            <a href="#" class="dropdown-item">
                <div class="dropdown-item-avatar">
                    <img alt="image" src="assets/img/avatar/avatar-5.png" class="rounded-circle">
                </div>
                <div class="dropdown-item-desc">
                    <b>Alfa Zulkarnain</b>
                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                    <div class="time">Yesterday</div>
                </div>
            </a>
        </div>
        <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
        </div>
    </div>
</li>

resources/views/layouts/sections/sidebar.blade.php
<div class="main-sidebar sidebar-style-2">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
            <a href="#">ILL MANAGER</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="#">ILL</a>
        </div>
        <ul class="sidebar-menu">

            <li class="{{ request()->is('admin/home') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.home') }}">
                    <i class="fas fa-tasks"></i> <span>Home</span>
                </a>
            </li>
            <li class="{{ request()->is('admin/requests/create') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.requests.create') }}">
                    <i class="fas fa-plus"></i> <span>New Request</span>
                </a>
            </li>
            <li class="{{ request()->is('admin/pulls') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.pulls.index') }}">
                    <i class="fas fa-truck"></i> <span>Pulls</span>
                </a>
            </li>
            <li class="{{ request()->is('admin/dashboard') ? 'active' : '' }}">
                <a class="nav-link" href="{{ route('admin.dashboard') }}">
                    <i class="fas fa-chart-bar"></i> <span>Dashboard</span>
                </a>
            </li>
            <li class="dropdown">
                <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-cogs"></i> <span>System</span></a>
                <ul class="dropdown-menu">
                    <li class="{{ request()->is('admin/users*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('admin.users.index') }}">Users</a></li>
                    <li class="{{ request()->is('admin/users/subjects*') ? 'active' : '' }}"><a class="nav-link" href="{{ route('admin.users.subjects.edit') }}">Assigned Subjects</a></li>
                </ul>
            </li>
            <li>
                <a class="nav-link" href="/telescope" target="_blank">
                    <i class="fas fa-bug"></i> <span>Telescope</span>
                </a>
            </li>

            @role('Super')
                <li>
                    <a class="nav-link" href="/horizon" target="_blank">
                        <i class="fas fa-user-md"></i> <span>Horizon</span>
                    </a>
                </li>
            @endrole
        </ul>
        @role('Super')
            <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
                <a href="https://demo.getstisla.com/index.html" class="btn btn-primary btn-lg btn-block btn-icon-split" target="_blank">
                    <i class="fas fa-rocket"></i> Documentation
                </a>
            </div>
        @endrole
    </aside>
</div>

resources/views/layouts/sections/user-menu.blade.php
<li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
    <div class="d-sm-none d-lg-inline-block">Hello, {{ auth()->check() ? auth()->user()->first_name : 'Guest' }}</div></a>
    <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item has-icon text-danger" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                     document.getElementById('logout-form').submit();">
            <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </div>
</li>