routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::middleware(['auth'])->name('admin.')->group(function () {

    Route::get('/', 'RequisitionController@index');
    Route::get('/home', 'RequisitionController@index')->name('home');
    Route::post('/requests/{request}/approve', 'RequisitionController@approve')->name('requests.approve');
    Route::get('/requests/{request}/cancel', 'RequisitionController@cancellation')->name('requests.cancellation');
    Route::post('/requests/{request}/cancel', 'RequisitionController@cancel')->name('requests.cancel');
    Route::post('/requests/{request}/add-message', 'RequisitionController@addMessage')->name('requests.messages.add');
    Route::post('/requests/{request}/mark-message-read', 'RequisitionController@markMessageRead')->name('requests.messages.read');
    Route::resource('/requests', 'RequisitionController');
    /*Route::post('/pulls/{pull}/add-message', 'PullsController@addMessage')->name('pulls.messages.add');*/
    Route::put('/pulls/{pull}/pulled', 'PullsController@pulled')->name('pulls.pulled');
    Route::put('/pulls/{pull}/missing', 'PullsController@missing')->name('pulls.missing');
    Route::get('/pulls/{pull}/print', 'PullsController@print')->name('pulls.print');
    Route::resource('/pulls', 'PullsController');

});

Route::middleware(['auth'])->prefix('admin')->name('admin.')->namespace('Admin')->group(function () {


    Route::get('/users/subjects/edit', 'SubjectUserController@edit')->name('users.subjects.edit');
    Route::put('/users/subjects/update', 'SubjectUserController@update')->name('users.subjects.update');

    Route::resource('/users', 'UserController');

    Route::get('/dashboard', 'DashboardController')->name('dashboard');

});

Auth::routes(['register' => false]);

app/Models/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles, SoftDeletes;

    protected $connection = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'receive_purchase_notifications'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get all of the user's messages.
     */
    public function messages()
    {
        return $this->morphMany(Message::class, 'messageable');
    }

    public function getFirstNameAttribute() {
        return explode(' ', $this->name)[0];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Foundation\Auth\SendsPasswordResetEmails;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Permission;
use App\Role;

class UserController extends \App\Http\Controllers\Controller
{
    use SendsPasswordResetEmails;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::whereHas("roles", function($q){ $q->where("name", "LIKE", "ILL%"); })->orderBy('name')->get();


        return view('admin.users.index', [
            'users' => $users,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = new User();
        $user->name = $request->get('name');
        $user->username = $request->get('username');
        $user->email = $request->get('email');
        $user->receive_purchase_notifications = $request->get('receive_purchase_notifications', 0);
        $user->password = Str::random(10);
        $user->save();

        $user->syncRoles('ILL Employee');

        $this->sendResetLinkEmail($request);

        return redirect()->route('admin.users.edit', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        return view('admin.users.edit', [
            'user' => $user,
            'roles' => Role::where('name', 'LIKE', 'ILL%')->get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->get('name');
        $user->username = $request->get('username');
        $user->email = $request->get('email');
        $user->receive_purchase_notifications = $request->get('receive_purchase_notifications', 0);
        $user->save();

        $user->syncRoles($request->get('role'));

        return redirect()->route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.users.index');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('page_name', 'Editing' )

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Editing {{ $user->name }}</h1>
        </div>

        <div class="row">
            <div class="col-lg-12 col-md-12 col-12">
                <div class="card">
                    <div class="card-body">
                        {!!Form::open()->fill($user)->patch()->route('admin.users.update', ['user' => $user->id])!!}

                            @include('admin.users.form')

                            {!!Form::submit("Update")!!}

                        {!!Form::close()!!}
                    </div>
                    <div class="card-footer text-right">
                        <nav class="d-inline-block">

                            {!!Form::open()->attrs(['class' => 'delete-form'])->delete()->route('admin.users.destroy', ['user' => $user])!!}
                                {!! Form::submit("Delete")->danger() !!}
                            {!!Form::close()!!}

                        </nav>
                    </div>
                </div>

            </div>
        </div>
    </section>


@endsection


@push('css')

@endpush

@push('scripts')

@endpush

resources/views/admin/users/form.blade.php
{!! Form::text('name', 'Name')->required() !!}
{!! Form::text('username', 'Username')->required() !!}

<div class="row">
    <div class="col">
        {!! Form::text('email', 'Email')->required() !!}
    </div>
    <div class="col" style="padding-top: 38px;">
        {!! Form::checkbox('receive_purchase_notifications', 'Receive Purchase Notifications', 1)->required(false) !!}
    </div>
</div>

<div class="row">
    <div class="col">
        {!! Form::select('role', 'Role', $roles->pluck('name', 'name')->all(), $user->getRoleNames()->first() )->required() !!}
    </div>
</div>

<div class="clearfix">&nbsp;</div>



@push('css')
    <style>

    </style>
@endpush

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('page_name', 'Subjects' )

@section('content')


    <section class="section">
        <div class="section-header">
            <h1>Users</h1>
        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-striped table-md">
                                <tbody><tr>
                                    <th></th>
                                    <th>Name</th>
                                    <th>Roles</th>
                                    <th></th>
                                    <th></th>
                                </tr>
                                @foreach ($users as $user)
                                    <tr>
                                        <td></td>
                                        <td>
                                            <a href="{{route('admin.users.edit', ['user' => $user]) }}" style="padding: 6px 8px">{{ $user->name }} </a>
                                        </td>
                                        <td>
                                            {{ $user->getRoleNames()->join(', ') }}
                                        </td>
                                        <td>

                                        </td>
                                        <td>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody></table>
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h4>New User</h4>
                    </div>
                    <div class="card-body">
                        {!!Form::open()->post()->route('admin.users.store')!!}

                        {!!Form::text('name', 'Name')->required()!!}
                        {!!Form::text('username', 'Username')->required()!!}
                        {!!Form::text('email', 'Email')->required()!!}
                        <div style="padding-top: 10px;">
                            {!! Form::checkbox('receive_purchase_notifications', 'Receive Purchase Notifications', 1)->checked(false)->required(false) !!}
                        </div>
                        <br />
                        {!!Form::submit("Save")!!}

                        {!!Form::close()!!}
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection


@push('css')

@endpush

@push('scripts')
    <script src="{{ asset('assets/js/page/components-table.js') }}"></script>
@endpush